### ISSUE TITLE
--zone is not recognized

### ISSUE THREAD

**Issue by 7c** [erikns/yucc#2]
Hi,
First of all thanks for this great tool!

based on your description --zone can be specified along `yucc server create` command. The command i am using

```
yucc server create --hostname sg002 --plan "1xCPU-1GB" --os "Ubuntu 16.04" --zone "sg-sin1"     --login-user vpn1 --ssh-key /root/.ssh/id_rsa.pub --ensure-started
==> You have not set a default deployment zone. It will need to be provided.
==> Zone is required
```

I have removed the default zone on purpose because, with it, it also did not recognize --zone option. What do i wrong please?

**Comment by erikns** [comment]
Hi,

Your're not doing anything wrong. In fact, it seems you have uncovered a bug. 🐛
It was caused by a silly mistake; the default was applied after the passed in `--zone`-parameter was parsed, even if the default was never set.

I just pushed a new release (v0.8.3) that should fix your issue :smile:. Please let me know if it still persists.
